### Q1

In [1]:
import numpy as np

xp = [0,3]
fp = [2, 5]
np.interp(2, xp, fp)

4.0

### Q2

In [2]:
arr = np.asmatrix([3,2,1])
arrT = arr.transpose()
print(arrT)

#Rotation Matrix
theta = np.radians(30)
c, s = np.cos(theta), np.sin(theta)
RoMatrix = np.asmatrix(((c, -s, 0), (s, c, 0), (0, 0, 1)))
print(RoMatrix)

#Transformation due to rotation
R = np.matmul(RoMatrix, arrT)
print(R)

#Translation Matrix
TransMatrix= np.asmatrix(((1,0,5), (0,1,7), (0,0,1)))
print(TransMatrix)

#Transformation due to translation
TransformedMatrix = np.matmul(TransMatrix,R)
print(TransformedMatrix)

[[3]
 [2]
 [1]]
[[ 0.8660254 -0.5        0.       ]
 [ 0.5        0.8660254  0.       ]
 [ 0.         0.         1.       ]]
[[1.59807621]
 [3.23205081]
 [1.        ]]
[[1 0 5]
 [0 1 7]
 [0 0 1]]
[[ 6.59807621]
 [10.23205081]
 [ 1.        ]]


In [3]:
arr1 = np.asmatrix([3,2,1,1])
arr1T = arr1.transpose()
print(arr1T)

z= np.asmatrix([0,0,0])
print(z)

trans = np.asmatrix([5,7,0,1])
print(trans)

#Transformation Matrix
H1 = np.concatenate((RoMatrix,z), axis=0)
H = np.concatenate((H1,trans.transpose()), axis=1)
print(H)

TransformedMatrix1 = np.matmul(H, arr1T)
print(TransformedMatrix1)

[[3]
 [2]
 [1]
 [1]]
[[0 0 0]]
[[5 7 0 1]]
[[ 0.8660254 -0.5        0.         5.       ]
 [ 0.5        0.8660254  0.         7.       ]
 [ 0.         0.         1.         0.       ]
 [ 0.         0.         0.         1.       ]]
[[ 6.59807621]
 [10.23205081]
 [ 1.        ]
 [ 1.        ]]


### Q3

In [4]:
from sympy import *

a0, a1, a2, x1, x2, x3, x  = symbols('a0, a1, a2, x1, x2, x3, x')
p = Poly( a0 + a1*x + a2*x**2, x)

c = p.all_coeffs()
c = np.flipud(c)
A = np.asmatrix(c).transpose()
print(c)

y = [p(0), p(1), p(2)]
Y = np.asmatrix(y).transpose()
print(Y)

X = []
x_values = [x1, x2, x3]
d = p.degree()+1
for x in x_values:
    for k in range(d):
        X.append(x**k)
        
X = np.asmatrix(X).reshape(3,3)
print(X)

Y = X*A
print(Y)

[a0 a1 a2]
[[a0]
 [a0 + a1 + a2]
 [a0 + 2*a1 + 4*a2]]
[[1 x1 x1**2]
 [1 x2 x2**2]
 [1 x3 x3**2]]
[[a0 + a1*x1 + a2*x1**2]
 [a0 + a1*x2 + a2*x2**2]
 [a0 + a1*x3 + a2*x3**2]]


In [5]:
x_matrix = []

def g(x):
    x2 = x**2
    x_matrix.append(x2)
    x1 = np.sin(x)
    x_matrix.append(x1)
    x0 = 1
    x_matrix.append(x0)
    return (1/10)*(x**2) + (-2)*(np.sin(x))

y = [g(0), g(1), g(2)]
Y_matrix = np.asmatrix(y)
print(Y_matrix)

X_matrix = np.asmatrix(x_matrix).reshape(3,3)
print(X_matrix)

a = np.linalg.inv(X_matrix)*Y_matrix.transpose()
print(a)

p = g(1.5)
print(p)

[[ 0.         -1.58294197 -1.41859485]]
[[0.         0.         1.        ]
 [1.         0.84147098 1.        ]
 [4.         0.90929743 1.        ]]
[[ 0.1]
 [-2. ]
 [ 0. ]]
-1.7699899732081088


### Q4

In [6]:
x = np.asmatrix([5,7]).transpose()
one = np.asmatrix([1])
X = np.concatenate((x,one),axis =0)
X

matrix([[5],
        [7],
        [1]])

### Q5

Two intersecting planes always form a. line.

In [7]:
a = Plane(Point3D(0, 3, 0), normal_vector=(2, 1, -1))
b = Plane(Point3D(3, 0, 0), normal_vector=(1, -1, 1))

print(a.intersection(b))

p1 = [2,-1,0]
p2 = [2, -4, -3]

d_vec = Line(p1, p2).direction
print(d_vec) 

t  = symbols('t')
x = poly(2 + t*0, t)
y = poly(-1 + t*(-3), t)
z = poly(t*(-3), t)

[Line3D(Point3D(2, -1, 0), Point3D(2, -4, -3))]
Point3D(0, -3, -3)


### Q6

In [8]:
L1 = Line(Point(-1/3,0), Point(0,-1/2))
print(L1.equation())

L2 = Line(Point(1/3,0), Point(0,1/2))
print(L2.equation())

print(L1.equals(L2))
print(Line.are_concurrent(L1,L2))
print(L1.intersection(L2))
print(L1.is_parallel(L2))
print(L1.is_perpendicular(L2))
print(L1.is_similar(L2))

x/2 + y/3 + 1/6
-x/2 - y/3 + 1/6
False
False
[]
True
False
False


In projective geometry, the parallel lines in Euclidean coordinate system intersects in Homogeneous coordinate system at inifinity and it is called as Vanishing Point.

In [9]:
l = np.asmatrix([3,2,1])
m = np.asmatrix([3,2,-1])

intersect_HC = np.cross(l,m)
intersect_HC = intersect_HC.T
print(intersect_HC)

[[-4]
 [ 6]
 [ 0]]


In [10]:
intersect_EC = intersect_HC/intersect_HC[2,0]
intersect_EC = np.delete(intersect_EC, 2, 0)

C:\Users\akank\AppData\Local\Temp\ipykernel_22472\3815327161.py:1: RuntimeWarning: divide by zero encountered in true_divide
  intersect_EC = intersect_HC/intersect_HC[2,0]
C:\Users\akank\AppData\Local\Temp\ipykernel_22472\3815327161.py:1: RuntimeWarning: invalid value encountered in true_divide
  intersect_EC = intersect_HC/intersect_HC[2,0]


### Q6

In [11]:
z= np.asmatrix([0,0,0])
zT = np.asmatrix([0, 0, 0, 1])
I = np.identity(3)

#Scaling Matrix
Scale = np.asmatrix(((5, 0, 0), (0, 1, 0), (0, 0, 1)))

A = np.concatenate((Scale,z), axis=0)
A = np.concatenate((A,zT.T), axis=1)
print(A)

#Rotation Matrix
theta = np.radians(30)
c, s = np.cos(theta), np.sin(theta)
Rotate = np.asmatrix(((c, -s, 0), (s, c, 0), (0, 0, 1)))

B = np.concatenate((Rotate,z), axis=0)
B = np.concatenate((B,zT.T), axis=1)
print(B)

#Shearing Matrix
Shear = np.asmatrix(((1, 2, 0), (3, 1, 0), (0, 0, 1)))

C = np.concatenate((Shear,z), axis=0)
C = np.concatenate((C,zT.T), axis=1)
print(C)

#Translation Matrix
#Trans = np.asmatrix(((1,0,2), (0,1,1), (0,0,2)))
Trans = np.asmatrix([2,1,2,1])
Trans = Trans.transpose()

D = np.concatenate((I,z), axis=0)
D = np.concatenate((D,Trans), axis=1)
print(D)

H = np.matmul(D,C)
H = np.matmul(H,B)
H = np.matmul(H,A)
print(H)

[[5 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[ 0.8660254 -0.5        0.         0.       ]
 [ 0.5        0.8660254  0.         0.       ]
 [ 0.         0.         1.         0.       ]
 [ 0.         0.         0.         1.       ]]
[[1 2 0 0]
 [3 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[1. 0. 0. 2.]
 [0. 1. 0. 1.]
 [0. 0. 1. 2.]
 [0. 0. 0. 1.]]
[[ 9.33012702  1.23205081  0.          2.        ]
 [15.49038106 -0.6339746   0.          1.        ]
 [ 0.          0.          1.          2.        ]
 [ 0.          0.          0.          1.        ]]


### Q7

In [12]:
#Writing 3D Point A in Homogeneous System
A= np.asmatrix([2,3,9,1])
A = A.transpose()
print(A)

z= np.asmatrix([0,0,0])
print(z)

#Translational Matrix
trans = np.asmatrix([8,0,5,1])
trans = trans.T
print(trans)

#Scaling Matrix
Scale = np.asmatrix(((5, 0, 0), (0, 1, 0), (0, 0, 1)))
print(Scale)

#Transformation Matrix
H = np.concatenate((Scale,z), axis=0)
H = np.concatenate((H,trans), axis=1)
print(H)

Transformed = np.matmul(H, A)
print(Transformed)

[[2]
 [3]
 [9]
 [1]]
[[0 0 0]]
[[8]
 [0]
 [5]
 [1]]
[[5 0 0]
 [0 1 0]
 [0 0 1]]
[[5 0 0 8]
 [0 1 0 0]
 [0 0 1 5]
 [0 0 0 1]]
[[18]
 [ 3]
 [14]
 [ 1]]


### Q8

In [13]:
#Method 1

#Writing 3D Point A in Homogeneous System
V= np.asmatrix([5,9,4,1])
V = V.transpose()
print(V)

z= np.asmatrix([0,0,0])
print(z)

#Translational Matrix
trans = np.asmatrix([4,-3,7,1])
trans = trans.T
print(trans)

#Rotation Matrix
theta = np.radians(30)
c_x, s_x = np.cos(theta), np.sin(theta)
R_X= np.asmatrix(((1, 0, 0), (0, c_x, -s_x), (0, s_x, c_x)))
print(R_X)

alpha = np.radians(90)
c_y, s_y = np.cos(alpha), np.sin(alpha)
R_Y = np.asmatrix(((c_y, 0, s_y), (0, 1, 0), (-s_y, 0, c_y)))
print(R_Y)

kappa = np.radians(180)
c_z, s_z = np.cos(kappa), np.sin(kappa)
R_Z = np.asmatrix(((c_z, -s_z, 0), (s_z, c_z, 0), (0, 0, 1)))
print(R_Z)

Rot = np.matmul(R_Y, R_X)
Rot = np.matmul(R_Z, Rot)
print(Rot)

#Transformation Matrix
H = np.concatenate((Rot,z), axis=0)
H = np.concatenate((H,trans), axis=1)
print(H)

Transformed = np.matmul(H, V)
print(Transformed)

[[5]
 [9]
 [4]
 [1]]
[[0 0 0]]
[[ 4]
 [-3]
 [ 7]
 [ 1]]
[[ 1.         0.         0.       ]
 [ 0.         0.8660254 -0.5      ]
 [ 0.         0.5        0.8660254]]
[[ 6.123234e-17  0.000000e+00  1.000000e+00]
 [ 0.000000e+00  1.000000e+00  0.000000e+00]
 [-1.000000e+00  0.000000e+00  6.123234e-17]]
[[-1.0000000e+00 -1.2246468e-16  0.0000000e+00]
 [ 1.2246468e-16 -1.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  1.0000000e+00]]
[[-6.12323400e-17 -5.00000000e-01 -8.66025404e-01]
 [ 7.49879891e-33 -8.66025404e-01  5.00000000e-01]
 [-1.00000000e+00  3.06161700e-17  5.30287619e-17]]
[[-6.12323400e-17 -5.00000000e-01 -8.66025404e-01  4.00000000e+00]
 [ 7.49879891e-33 -8.66025404e-01  5.00000000e-01 -3.00000000e+00]
 [-1.00000000e+00  3.06161700e-17  5.30287619e-17  7.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[-3.96410162]
 [-8.79422863]
 [ 2.        ]
 [ 1.        ]]


In [14]:
#Method 2

V= np.asmatrix([5,9,4])
V = V.transpose()
print(V)

#Translational Matrix
translation = np.asmatrix(((1, 0, 4),(0, 1, -3), (0, 0, 7)))

rotated = np.matmul(Rot, V)
print(rotated)

Transformed = np.matmul(translation, rotated)
print(Transformed)

one = np.asmatrix([1])
X = np.concatenate((Transformed,one),axis =0)
X #Different results that I couldn't correct

[[5]
 [9]
 [4]]
[[-7.96410162]
 [-5.79422863]
 [-5.        ]]
[[-27.96410162]
 [  9.20577137]
 [-35.        ]]


matrix([[-27.96410162],
        [  9.20577137],
        [-35.        ],
        [  1.        ]])

### Q9

In [15]:
image_coords =[(880, 214), (43, 203), (270, 197), (886, 347), (745, 302), 
             (943, 128), (476, 590), (419, 214), (317, 335), (783, 521), 
             (235, 427), (665, 429), (665, 362), (427, 333), (412, 415), 
             (746, 351), (434, 415), (525, 234), (716, 308), (602, 187)]

image_coords = np.reshape(image_coords, (20,2))
print(image_coords)

world_coords = [(312.747, 309.140, 30.086), (305.796, 311.649, 30.356), 
             (307.694, 312.358, 30.418), (310.149, 307.186, 29.298), 
             (311.937, 310.105, 29.216), (311.202, 307.572, 30.682), 
             (307.106, 306.876, 28.660), (309.317, 312.490, 30.230), 
             (307.435, 310.151, 29.318), (308.253, 306.300, 28.881), 
             (306.650, 309.301, 28.905), (308.069, 306.831, 29.189), 
             (309.671, 308.834, 29.029), (308.255, 309.955, 29.267), 
             (307.546, 308.613, 28.963), (311.036, 309.206, 28.913), 
             (307.518, 308.175, 29.069), (309.950, 311.262, 29.990), 
             (312.160, 310.772, 29.080), (311.988, 312.709, 30.514)]

world_coords = np.reshape(world_coords, (20,3))
print(world_coords)

[[880 214]
 [ 43 203]
 [270 197]
 [886 347]
 [745 302]
 [943 128]
 [476 590]
 [419 214]
 [317 335]
 [783 521]
 [235 427]
 [665 429]
 [665 362]
 [427 333]
 [412 415]
 [746 351]
 [434 415]
 [525 234]
 [716 308]
 [602 187]]
[[312.747 309.14   30.086]
 [305.796 311.649  30.356]
 [307.694 312.358  30.418]
 [310.149 307.186  29.298]
 [311.937 310.105  29.216]
 [311.202 307.572  30.682]
 [307.106 306.876  28.66 ]
 [309.317 312.49   30.23 ]
 [307.435 310.151  29.318]
 [308.253 306.3    28.881]
 [306.65  309.301  28.905]
 [308.069 306.831  29.189]
 [309.671 308.834  29.029]
 [308.255 309.955  29.267]
 [307.546 308.613  28.963]
 [311.036 309.206  28.913]
 [307.518 308.175  29.069]
 [309.95  311.262  29.99 ]
 [312.16  310.772  29.08 ]
 [311.988 312.709  30.514]]


In [16]:
A = np.zeros((2*len(world_coords), 12))

for i in range(0, A.shape[0], 2):
    A[i, 0] = world_coords[int(i/2)][0]
    A[i, 1] = world_coords[int(i/2)][1]
    A[i, 2] = world_coords[int(i/2)][2]
    A[i, 3] = 1
    A[i, 8] = -1 * image_coords[int(i/2)][0] * world_coords[int(i/2)][0]
    A[i, 9] = -1 * image_coords[int(i/2)][0] * world_coords[int(i/2)][1]
    A[i, 10] = -1 * image_coords[int(i/2)][0] * world_coords[int(i/2)][2]
    A[i, 11] = -1 * image_coords[int(i/2)][0]
    A[i+1, 4] = world_coords[int(i/2)][0]
    A[i+1, 5] = world_coords[int(i/2)][1]
    A[i+1, 6] = world_coords[int(i/2)][2]
    A[i+1, 7] = 1
    A[i+1, 8] = -1 * image_coords[int(i/2)][1] * world_coords[int(i/2)][0]
    A[i+1, 9] = -1 * image_coords[int(i/2)][1] * world_coords[int(i/2)][1]
    A[i+1, 10] = -1 * image_coords[int(i/2)][1] * world_coords[int(i/2)][2]
    A[i+1, 11] = -1 * image_coords[int(i/2)][1]

print(A)

[[ 3.12747000e+02  3.09140000e+02  3.00860000e+01  1.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  -2.75217360e+05 -2.72043200e+05 -2.64756800e+04 -8.80000000e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   3.12747000e+02  3.09140000e+02  3.00860000e+01  1.00000000e+00
  -6.69278580e+04 -6.61559600e+04 -6.43840400e+03 -2.14000000e+02]
 [ 3.05796000e+02  3.11649000e+02  3.03560000e+01  1.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  -1.31492280e+04 -1.34009070e+04 -1.30530800e+03 -4.30000000e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   3.05796000e+02  3.11649000e+02  3.03560000e+01  1.00000000e+00
  -6.20765880e+04 -6.32647470e+04 -6.16226800e+03 -2.03000000e+02]
 [ 3.07694000e+02  3.12358000e+02  3.04180000e+01  1.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  -8.30773800e+04 -8.43366600e+04 -8.21286000e+03 -2.70000000e+02]
 [ 0.

In [17]:
U, S, Vh = np.linalg.svd(A)
V = Vh.T

M = Vh[-1,:]
M = np.reshape(M, (3,4))

print(M)

[[ 3.09551512e-03  1.50099363e-04 -4.55089945e-04 -9.78699360e-01]
 [ 3.08995055e-04  6.37417029e-04 -2.76003823e-03 -2.05250740e-01]
 [ 1.68238445e-06  2.74302661e-06 -6.69612696e-07 -1.32883746e-03]]


In [18]:
H = np.delete(M, 3, axis=1)
print(H)

#Decomposition
q, r = np.linalg.qr(np.linalg.inv(H))

R = q.T
print(R)

#Normalisation of K
K = np.linalg.inv(r)
print(K)

#R(z, pi)
kappa = np.radians(180)
c_z, s_z = np.cos(kappa), np.sin(kappa)
R_z = np.asmatrix(((c_z, -s_z, 0), (s_z, c_z, 0), (0, 0, 1)))
print(R_Z)

K = np.matmul(K, R_z)
R = np.matmul(R_z, R)
print(K)
print(R)

#Finding translational matrix
H = np.matmul(K,R)
print(H)

h = M[:,-1]
print(h)

t = np.matmul(np.linalg.inv(K), h)
print(t)

[[ 3.09551512e-03  1.50099363e-04 -4.55089945e-04]
 [ 3.08995055e-04  6.37417029e-04 -2.76003823e-03]
 [ 1.68238445e-06  2.74302661e-06 -6.69612696e-07]]
[[-0.84921374  0.52737269  0.02672191]
 [-0.12974186 -0.15933104 -0.97866269]
 [-0.51186235 -0.83456076  0.20372842]]
[[-2.56175655e-03  1.98461690e-05 -1.80245944e-03]
 [ 0.00000000e+00  2.55949654e-03 -1.25242441e-03]
 [-0.00000000e+00 -0.00000000e+00 -3.28679077e-06]]
[[-1.0000000e+00 -1.2246468e-16  0.0000000e+00]
 [ 1.2246468e-16 -1.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  1.0000000e+00]]
[[ 2.56175655e-03 -1.98461690e-05 -1.80245944e-03]
 [ 3.13447925e-19 -2.55949654e-03 -1.25242441e-03]
 [ 0.00000000e+00  0.00000000e+00 -3.28679077e-06]]
[[ 0.84921374 -0.52737269 -0.02672191]
 [ 0.12974186  0.15933104  0.97866269]
 [-0.51186235 -0.83456076  0.20372842]]
[[ 3.09551512e-03  1.50099363e-04 -4.55089945e-04]
 [ 3.08995055e-04  6.37417029e-04 -2.76003823e-03]
 [ 1.68238445e-06  2.74302661e-06 -6.69612696e-07]]
[-0

### Q10

In [19]:
M = np.asmatrix(((512, -800, 0, 800), (512, 0, -800, 1600), (1, 0, 0, 0)))
print(M)

W = np.asmatrix((4,0,0)).T
print(W)

[[ 512 -800    0  800]
 [ 512    0 -800 1600]
 [   1    0    0    0]]
[[4]
 [0]
 [0]]
